package com.luky.nexusmind.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.luky.nexusmind.client.DeepSeekClient;
import com.luky.nexusmind.client.GenerationCancellation;
import com.luky.nexusmind.agent.AgentContext;
import com.luky.nexusmind.agent.AgentEvent;
import com.luky.nexusmind.agent.AgentOrchestrator;
import com.luky.nexusmind.entity.SearchResult;
import com.luky.nexusmind.model.ChatSession;
import com.luky.nexusmind.model.FileUpload;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.core.task.TaskExecutor;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.ConcurrentHashMap;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Set;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final ObjectMapper objectMapper;
    private final AiTraceService aiTraceService;
    private final ChatSessionService chatSessionService;
    private final AgentOrchestrator agentOrchestrator;
    private final ChatScopeService chatScopeService;
    private final TaskExecutor chatTitleExecutor;

    @Autowired(required = false)
    private KnowledgeGraphRetrievalService graphRetrievalService;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    private final Map<String, GenerationCancellation> generationCancellations = new ConcurrentHashMap<>();
    private final Map<String, List<AgentEvent>> agentEvents = new ConcurrentHashMap<>();
    private final Set<Long> titleTasks = ConcurrentHashMap.newKeySet();

    public ChatHandler(HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      AiTraceService aiTraceService,
                      ChatSessionService chatSessionService) {
        this(searchService, deepSeekClient, aiTraceService, chatSessionService,
                (AgentOrchestrator) null, null, Runnable::run);
    }

    @Autowired
    public ChatHandler(HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      AiTraceService aiTraceService,
                      ChatSessionService chatSessionService,
                      ObjectProvider<AgentOrchestrator> agentOrchestratorProvider,
                      ChatScopeService chatScopeService,
                      @Qualifier("chatTitleExecutor") TaskExecutor chatTitleExecutor) {
        this(searchService, deepSeekClient, aiTraceService, chatSessionService,
                agentOrchestratorProvider != null ? agentOrchestratorProvider.getIfAvailable() : null,
                chatScopeService, chatTitleExecutor);
    }

    private ChatHandler(HybridSearchService searchService,
                       DeepSeekClient deepSeekClient,
                       AiTraceService aiTraceService,
                       ChatSessionService chatSessionService,
                       AgentOrchestrator agentOrchestrator,
                       ChatScopeService chatScopeService,
                       TaskExecutor chatTitleExecutor) {
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.aiTraceService = aiTraceService;
        this.chatSessionService = chatSessionService;
        this.agentOrchestrator = agentOrchestrator;
        this.chatScopeService = chatScopeService;
        this.chatTitleExecutor = chatTitleExecutor;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        processMessage(userId, userMessage, session, userId);
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session, String traceUserId) {
        Long chatSessionId = chatSessionService.createSession(userId).getId();
        processMessage(userId, chatSessionId, userMessage, session, traceUserId);
    }

    public void processMessage(String userId, Long chatSessionId, String userMessage, WebSocketSession session) {
        processMessage(userId, chatSessionId, userMessage, session, userId);
    }

    public void processMessage(String userId,
                               Long chatSessionId,
                               String userMessage,
                               WebSocketSession session,
                               String traceUserId) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        AiTraceService.TraceSpan traceSpan = AiTraceService.TraceSpan.noop();
        AtomicBoolean traceFinished = new AtomicBoolean(false);
        long thinkingStartedAtNanos = System.nanoTime();
        AtomicLong thinkingDurationMs = new AtomicLong(-1L);
        GenerationCancellation cancellation = new GenerationCancellation();
        GenerationCancellation previous = generationCancellations.put(session.getId(), cancellation);
        if (previous != null) previous.cancel();
        try {
            // 1. 校验并使用显式会话 ID
            ChatSession chatSession = chatSessionService.getOwnedActiveSession(userId, chatSessionId);
            List<FileUpload> scopeFiles = chatScopeService == null
                    ? List.of()
                    : chatScopeService.resolveFiles(userId, chatSession);
            String conversationId = String.valueOf(chatSessionId);
            String effectiveTraceUserId = hasText(traceUserId) ? traceUserId : userId;
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            if (!chatSession.isTitleGenerated()) {
                String titleInput = "新会话".equals(chatSession.getTitle()) ? userMessage : chatSession.getTitle();
                generateTitleAsync(userId, chatSessionId, titleInput, session);
            }
            traceSpan = aiTraceService.startSpan("rag.chat", effectiveTraceUserId, session.getId(), conversationId)
                    .attribute("nexusmind.input.length", userMessage != null ? userMessage.length() : 0);
            if (aiTraceService.shouldCaptureContent()) {
                traceSpan.attribute("input.value", abbreviate(userMessage, 2000));
            }
            final AiTraceService.TraceSpan currentTrace = traceSpan;
            
            // 为当前会话创建响应构建器
            responseBuilders.put(session.getId(), new StringBuilder());
            agentEvents.put(session.getId(), Collections.synchronizedList(new ArrayList<>()));
            
            // 2. 获取对话历史
            List<Map<String, String>> history = chatSessionService.getRecentHistory(userId, chatSessionId, 20);
            logger.debug("获取到 {} 条历史对话", history.size());
            currentTrace.attribute("nexusmind.history.count", history.size());

            // 优先使用受控 Tool Calling；模型或协议不兼容时自动回退原有固定 RAG。
            if (agentOrchestrator != null && agentOrchestrator.isEnabled()) {
                try {
                    AgentContext agentContext = new AgentContext(
                            userId, chatSessionId, session.getId(), effectiveTraceUserId,
                            scopeFiles.stream().map(FileUpload::getId).toList(),
                            scopeFiles.stream().map(FileUpload::getFileMd5).toList());
                    currentTrace.attribute("nexusmind.agent.enabled", true);
                    agentOrchestrator.run(userId, userMessage, history, agentContext, cancellation,
                            event -> {
                                if (!cancellation.isCancelled()) recordAndSendAgentEvent(session, event);
                            },
                            chunk -> {
                                if (cancellation.isCancelled()) return;
                                captureThinkingDuration(thinkingStartedAtNanos, thinkingDurationMs);
                                StringBuilder responseBuilder = responseBuilders.get(session.getId());
                                if (responseBuilder != null) responseBuilder.append(chunk);
                                sendResponseChunk(session, chunk);
                            },
                            error -> {
                                if (!cancellation.isCancelled()) {
                                    handleError(session, error);
                                    currentTrace.error(error);
                                }
                                finishTrace(currentTrace, traceFinished);
                                cleanupGeneration(session, cancellation);
                            },
                            () -> {
                                if (cancellation.isCancelled()) {
                                    completeCancelled(session, currentTrace, traceFinished, cancellation);
                                } else {
                                    completeResponse(userId, chatSessionId, userMessage, session,
                                            currentTrace, traceFinished, thinkingStartedAtNanos, thinkingDurationMs,
                                            agentContext::repairIncompleteSourceIds);
                                    generationCancellations.remove(session.getId(), cancellation);
                                }
                            });
                    return;
                } catch (RuntimeException agentError) {
                    if (cancellation.isCancelled()) {
                        completeCancelled(session, currentTrace, traceFinished, cancellation);
                        return;
                    }
                    logger.warn("Tool Calling 不可用，回退固定 RAG: {}", agentError.getMessage());
                    currentTrace.attribute("nexusmind.agent.fallback", true);
                    responseBuilders.put(session.getId(), new StringBuilder());
                }
            }
            
            // 3. 执行带权限过滤的混合搜索
            List<SearchResult> searchResults;
            AiTraceService.TraceSpan searchSpan = aiTraceService.startSpan(
                    "rag.hybrid_search", effectiveTraceUserId, session.getId(), conversationId)
                    .attribute("nexusmind.search.top_k", 5)
                    .attribute("nexusmind.search.query.length", userMessage != null ? userMessage.length() : 0);
            try {
                searchResults = searchService.searchWithPermission(
                        userMessage, userId, 5,
                        scopeFiles.stream().map(FileUpload::getFileMd5).collect(java.util.stream.Collectors.toSet()));
                searchSpan.attribute("nexusmind.search.results.count", searchResults.size());
            } catch (RuntimeException e) {
                searchSpan.error(e);
                currentTrace.error(e);
                throw e;
            } finally {
                searchSpan.end();
                searchSpan.close();
            }
            logger.debug("搜索结果数量: {}", searchResults.size());
            if (cancellation.isCancelled()) {
                completeCancelled(session, currentTrace, traceFinished, cancellation);
                return;
            }
            
            // 4. 构建上下文
            String context;
            AiTraceService.TraceSpan contextSpan = aiTraceService.startSpan(
                    "rag.context.build", effectiveTraceUserId, session.getId(), conversationId)
                    .attribute("nexusmind.search.results.count", searchResults.size());
            try {
                context = buildContext(searchResults);
                if (graphRetrievalService != null) {
                    String graphContext = graphRetrievalService.buildContext(
                            userId, userMessage, searchResults, scopeFiles.stream().map(FileUpload::getId).toList());
                    if (!graphContext.isBlank()) {
                        context = context + "\n" + graphContext;
                    }
                }
                contextSpan.attribute("nexusmind.context.length", context.length());
            } catch (RuntimeException e) {
                contextSpan.error(e);
                currentTrace.error(e);
                throw e;
            } finally {
                contextSpan.end();
                contextSpan.close();
            }
            currentTrace.attribute("nexusmind.search.results.count", searchResults.size())
                    .attribute("nexusmind.context.length", context.length());
            if (cancellation.isCancelled()) {
                completeCancelled(session, currentTrace, traceFinished, cancellation);
                return;
            }
            
            // 5. 调用 DeepSeek API 并处理流式响应
            logger.info("调用DeepSeek API生成回复");
            deepSeekClient.streamResponse(userMessage, context, history, 
                userId,
                effectiveTraceUserId,
                session.getId(),
                conversationId,
                cancellation,
                chunk -> {
                    if (cancellation.isCancelled()) return;
                    captureThinkingDuration(thinkingStartedAtNanos, thinkingDurationMs);
                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    if (!cancellation.isCancelled()) {
                        handleError(session, error);
                        currentTrace.error(error);
                    }
                    finishTrace(currentTrace, traceFinished);
                    cleanupGeneration(session, cancellation);
                },
                () -> {
                    if (cancellation.isCancelled()) {
                        completeCancelled(session, currentTrace, traceFinished, cancellation);
                    } else {
                        completeResponse(userId, chatSessionId, userMessage, session, currentTrace, traceFinished,
                                thinkingStartedAtNanos, thinkingDurationMs, java.util.function.UnaryOperator.identity());
                        generationCancellations.remove(session.getId(), cancellation);
                    }
                });
            
        } catch (Exception e) {
            if (!cancellation.isCancelled()) {
                logger.error("处理消息错误: {}", e.getMessage(), e);
                traceSpan.error(e);
                handleError(session, e);
            }
            finishTrace(traceSpan, traceFinished);
            cleanupGeneration(session, cancellation);
        } finally {
            traceSpan.close();
        }
    }

    private void completeResponse(String userId,
                                  Long chatSessionId,
                                  String userMessage,
                                  WebSocketSession session,
                                  AiTraceService.TraceSpan currentTrace,
                                  AtomicBoolean traceFinished,
                                  long thinkingStartedAtNanos,
                                  AtomicLong thinkingDurationMs,
                                  java.util.function.UnaryOperator<String> responseNormalizer) {
        try {
            StringBuilder responseBuilder = responseBuilders.get(session.getId());
            if (responseBuilder == null) {
                RuntimeException exception = new RuntimeException("响应构建器为空");
                logger.warn("响应构建器为空，可能出现了错误，会话ID: {}", session.getId());
                currentTrace.error(exception);
                handleError(session, exception);
                return;
            }

            String rawResponse = responseBuilder.toString();
            String completeResponse = responseNormalizer.apply(rawResponse);
            if (!completeResponse.equals(rawResponse)) sendContentReplacement(session, completeResponse);
            currentTrace.attribute("output.length", completeResponse.length());
            if (aiTraceService.shouldCaptureContent()) {
                currentTrace.attribute("output.value", abbreviate(completeResponse, 2000));
            }
            currentTrace.attribute("nexusmind.llm.stream.completed", true)
                    .attribute("nexusmind.trace.end_reason", "llm_stream_complete");

            captureThinkingDuration(thinkingStartedAtNanos, thinkingDurationMs);
            persistCompletedExchange(userId, chatSessionId, userMessage, completeResponse, session,
                    thinkingDurationMs.get());
            sendCompletionNotification(session, chatSessionId);
            logger.info("消息处理完成，用户ID: {}, 会话ID: {}", userId, chatSessionId);
        } catch (Exception e) {
            logger.error("完成响应处理时出错: {}", e.getMessage(), e);
            currentTrace.error(e);
            handleError(session, e);
        } finally {
            responseBuilders.remove(session.getId());
            agentEvents.remove(session.getId());
            finishTrace(currentTrace, traceFinished);
        }
    }

    private void completeCancelled(WebSocketSession session,
                                   AiTraceService.TraceSpan trace,
                                   AtomicBoolean traceFinished,
                                   GenerationCancellation cancellation) {
        trace.attribute("nexusmind.trace.end_reason", "user_cancelled");
        cleanupGeneration(session, cancellation);
        finishTrace(trace, traceFinished);
    }

    private void cleanupGeneration(WebSocketSession session, GenerationCancellation cancellation) {
        if (!generationCancellations.remove(session.getId(), cancellation)) return;
        responseBuilders.remove(session.getId());
        agentEvents.remove(session.getId());
    }

    private void persistCompletedExchange(String userId,
                                          Long chatSessionId,
                                          String userMessage,
                                          String completeResponse,
                                          WebSocketSession session,
                                          long thinkingDurationMs) {
        String agentTrace = serializeAgentTrace(session.getId());
        chatSessionService.appendCompletedExchange(
                userId, chatSessionId, userMessage, completeResponse, null, agentTrace, thinkingDurationMs);
        logger.info("对话已持久化到数据库，会话ID: {}", chatSessionId);
    }

    private void generateTitleAsync(String userId,
                                    Long chatSessionId,
                                    String userMessage,
                                    WebSocketSession session) {
        if (!titleTasks.add(chatSessionId)) {
            return;
        }
        try {
            String fallback = chatSessionService.ensureFallbackTitle(userId, chatSessionId, userMessage);
            if (fallback != null) {
                sendTitleUpdateNotification(session, chatSessionId, fallback);
            }
            chatTitleExecutor.execute(() -> {
                try {
                    String title = deepSeekClient.generateTitle(userId, userMessage);
                    if (!hasText(title)) {
                        logger.warn("标题模型未返回有效内容，会话ID: {}", chatSessionId);
                        return;
                    }
                    String storedTitle = chatSessionService.updateGeneratedTitle(userId, chatSessionId, title);
                    if (storedTitle != null) {
                        sendTitleUpdateNotification(session, chatSessionId, storedTitle);
                    } else {
                        logger.warn("标题模型输出未通过校验或会话已改名，会话ID: {}", chatSessionId);
                    }
                } catch (RuntimeException e) {
                    logger.warn("更新会话标题失败，会话ID: {}, 错误: {}", chatSessionId, e.getMessage());
                } finally {
                    titleTasks.remove(chatSessionId);
                }
            });
        } catch (RuntimeException e) {
            titleTasks.remove(chatSessionId);
            logger.warn("会话标题初始化失败，会话ID: {}, 错误: {}", chatSessionId, e.getMessage());
        }
    }

    private void captureThinkingDuration(long startedAtNanos, AtomicLong durationMs) {
        long elapsedMs = Math.max(0L, (System.nanoTime() - startedAtNanos) / 1_000_000L);
        durationMs.compareAndSet(-1L, elapsedMs);
    }

    private String buildContext(List<SearchResult> searchResults) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 返回空字符串，让 DeepSeekClient 按"无检索结果"逻辑处理
            return "";
        }

        final int MAX_SNIPPET_LEN = 300; // 单段最长字符数，超出截断
        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getTextContent();
            if (snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "…";
            }
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            context.append(String.format("[%d] (%s) %s\n", i + 1, fileLabel, snippet));
        }
        return context.toString();
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            GenerationCancellation cancellation = generationCancellations.get(session.getId());
            if (cancellation != null && cancellation.isCancelled()) return;
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            sendMessage(session, jsonChunk);
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void recordAndSendAgentEvent(WebSocketSession session, AgentEvent event) {
        List<AgentEvent> events = agentEvents.get(session.getId());
        if (events != null) {
            synchronized (events) {
                int existing = -1;
                for (int i = 0; i < events.size(); i++) {
                    if (events.get(i).stepId().equals(event.stepId())) {
                        existing = i;
                        break;
                    }
                }
                if (existing >= 0) events.set(existing, event);
                else events.add(event);
            }
        }
        try {
            sendMessage(session, objectMapper.writeValueAsString(event));
        } catch (Exception e) {
            logger.warn("发送 Agent 状态事件失败: {}", e.getMessage());
        }
    }

    private String serializeAgentTrace(String websocketSessionId) {
        List<AgentEvent> events = agentEvents.get(websocketSessionId);
        if (events == null || events.isEmpty()) return null;
        try {
            List<Map<String, Object>> completed = new ArrayList<>();
            synchronized (events) {
                for (AgentEvent event : events) {
                    Map<String, Object> item = objectMapper.convertValue(event, Map.class);
                    if ("running".equals(item.get("status"))) item.put("status", "completed");
                    completed.add(item);
                }
            }
            return objectMapper.writeValueAsString(completed);
        } catch (Exception e) {
            logger.warn("序列化 Agent 执行轨迹失败: {}", e.getMessage());
            return null;
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        sendCompletionNotification(session, null);
    }

    private void sendContentReplacement(WebSocketSession session, String content) {
        try {
            sendMessage(session, objectMapper.writeValueAsString(
                    Map.of("type", "content_replaced", "content", content)));
        } catch (Exception e) {
            logger.warn("发送校正后的回答失败: {}", e.getMessage());
        }
    }

    private void sendCompletionNotification(WebSocketSession session, Long chatSessionId) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = new HashMap<>();
            notification.put("type", "completion");
            notification.put("status", "finished");
            notification.put("message", "响应已完成");
            notification.put("timestamp", currentTime);
            notification.put("date", java.time.LocalDateTime.now().toString());
            if (chatSessionId != null) {
                notification.put("sessionId", chatSessionId);
            }
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            sendMessage(session, notificationJson);
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void sendTitleUpdateNotification(WebSocketSession session, Long chatSessionId, String title) {
        try {
            Map<String, Object> notification = new HashMap<>();
            notification.put("type", "title_updated");
            notification.put("sessionId", chatSessionId);
            notification.put("title", title);
            String notificationJson = objectMapper.writeValueAsString(notification);
            sendMessage(session, notificationJson);
        } catch (Exception e) {
            logger.warn("发送标题更新通知失败，会话ID: {}, 错误: {}", chatSessionId, e.getMessage());
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            sendMessage(session, errorJson);
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    private void finishTrace(AiTraceService.TraceSpan span, AtomicBoolean finished) {
        if (finished.compareAndSet(false, true)) {
            span.end();
        }
    }

    private void sendMessage(WebSocketSession session, String payload) throws java.io.IOException {
        synchronized (session) {
            session.sendMessage(new TextMessage(payload));
        }
    }

    private String abbreviate(String value, int maxLength) {
        if (value == null || value.length() <= maxLength) {
            return value;
        }
        return value.substring(0, maxLength) + "...";
    }

    private boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }

    /**
     * 停止响应 
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);
        
        GenerationCancellation cancellation = generationCancellations.get(sessionId);
        if (cancellation != null) cancellation.cancel();
        
        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop", 
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            sendMessage(session, stopJson);
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }
        
    }
}
