/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types'

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      icon: 'solar:chat-round-call-line-duotone',
      order: 1
    }
  },
  {
    name: 'chat-history',
    path: '/chat-history',
    component: 'layout.base$view.chat-history',
    meta: {
      title: 'chat-audit',
      i18nKey: 'route.chat-history',
      icon: 'solar:hashtag-chat-broken',
      order: 2
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge-base',
    path: '/knowledge-base',
    component: 'layout.base$view.knowledge-base',
    meta: {
      title: 'knowledge-base',
      i18nKey: 'route.knowledge-base',
      icon: 'solar:folder-line-duotone',
      order: 3
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'model-config',
    path: '/model-config',
    component: 'layout.base$view.model-config',
    meta: {
      title: 'model-config',
      i18nKey: 'route.model-config',
      icon: 'solar:settings-minimalistic-line-duotone',
      order: 7
    }
  },
  {
    name: 'observability',
    path: '/observability',
    component: 'layout.base$view.observability',
    meta: {
      title: 'observability',
      i18nKey: 'route.observability',
      icon: 'solar:chart-2-line-duotone',
      order: 8
    }
  },
  {
    name: 'org-tag',
    path: '/org-tag',
    component: 'layout.base$view.org-tag',
    meta: {
      title: 'org-tag',
      i18nKey: 'route.org-tag',
      icon: 'solar:tag-line-duotone',
      roles: ['ADMIN'],
      order: 5
    }
  },
  {
    name: 'organization-graph',
    path: '/organization-graph',
    component: 'layout.base$view.organization-graph',
    meta: {
      title: 'organization-graph',
      i18nKey: 'route.organization-graph',
      icon: 'solar:share-circle-line-duotone',
      order: 4
    }
  },
  {
    name: 'personal-center',
    path: '/personal-center',
    component: 'layout.base$view.personal-center',
    meta: {
      title: 'personal-center',
      i18nKey: 'route.personal-center',
      icon: 'solar:people-nearby-line-duotone',
      order: 9
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'solar:user-line-duotone',
      roles: ['ADMIN'],
      order: 6
    }
  }
];
